### ISSUE TITLE
Error on install run octosuite

### ISSUE THREAD

**Issue by gusantoscode** [rly0nheart/octosuite#2]
I've tried installing octosuite by pip and cloning the source code, but both have the same error.
I already installed all requirements in requirements.txt

---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

```
                 OCTOSUITE © 2022 Richard Mwewa
               Tuesday 24 May 2022, 12:22:35PM
            
            
        Linux
	├─ Processor: x86_64
	├─ Node: (my_pc_username)
	├─ Release: 5.15.0-27-generic
	├─ Architecture: ('64bit', 'ELF')
	├─ Version: #28-Ubuntu SMP Thu Apr 14 04:55:28 UTC 2022


Traceback (most recent call last):
  File "/home/my_username/.local/bin/octosuite", line 5, in <module>
    from octosuite.main import run
  File "/home/my_username/.local/lib/python3.10/site-packages/octosuite/main.py", line 9, in <module>
    from octosuite import colors,banner
  File "/home/my_username/.local/lib/python3.10/site-packages/octosuite/colors.py", line 36, in <module>
    color_chooser = input(f"[ ? ] Welcome {os.getlogin()}, would you like to enable colors for this session? (y/n) ")
OSError: [Errno 6] No such device or address

```

**Comment by rly0nheart** [comment]
Hello, please use the Issue template to provide more details about the error you're getting.

**Comment by gusantoscode** [comment]
Well, I just installed octosuite normally and started it in the terminal. However, when I start it shows this error, it doesn't even work. When I give ./octosuite in the directory or octosuite (installed via pip) in the terminal it just returns this error that was described.

**Comment by gusantoscode** [comment]
**Describe the bug**
Well, I just installed octosuite normally and started it in the terminal. However, when I start it shows this error, it doesn't even work. When I give ./octosuite in the directory or octosuite (installed via pip) in the terminal it just returns this error that was described.

**To Reproduce**
Steps to reproduce the behavior:
1. Install octosuite by cloning the github project or install it via pip.
2. Open terminal and run octosuite
3. See error

**Expected behavior**
Well, I expected it to work correctly, without showing any errors.

**Screenshots**
![Screenshot from 2022-05-24 18-55-52](https://user-images.githubusercontent.com/29460193/170140848-889e01f2-9966-4c9f-bc3d-8313a16fd07b.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu Budgie - 64-Bit
 - OS-Version: 10.6.1
 - Python Version: 3.10.4
